spring:
  mvc:
    problemdetails:
      enabled: true
    log-resolved-exception: false
  web:
    locale: zh # 默认为中文
server:
  error:
    include-stacktrace: never
  port: 80
wares:
  validator-fast-failed: true # 开启校验器快速失败
  async:
    enable: false
