spring:
  mvc:
    problemdetails:
      enabled: true
    log-resolved-exception: true
  web:
    locale: zh # 默认为中文
server:
  error:
    include-stacktrace: never
wares:
  validator-fast-failed: true # 开启校验器快速失败
